# Use root/example as user/password credentials
version: '3.1'

services:

    mongo:
        image: mongo:4.4.2-bionic
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - mongodb:/data/db
        ports:
            - 27017:27017
        networks:
            - mongo

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
        networks:
            - mongo

volumes:
    mongodb:
        driver: local

networks:
    mongo:
        driver: bridge
