version: '3.1'

services:

    db:
        image: postgres:13.1
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - /home/mrj/MrJ/rust/chain_scraper/db:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8090:8080