version: '3.1'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        container_name: elasticsearch
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.2
        environment:
            ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
            SERVER_NAME: "chain_scraper_kibana"
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        ports:
            - 5601:5601/tcp
        networks:
            - elastic

volumes:
    elasticsearch:
        driver: local

networks:
    elastic:
        driver: bridge
